#
# USB peripheral controller drivers
#

#CONFIG_HIUSB_DEVICE2_0=m
#CONFIG_USB_HISI_UDC=m
CONFIG_USB_HISI_UDC3=m
CONFIG_USB_DWC3=m


obj-$(CONFIG_USB_GADGET)	+= udc-core.o
obj-$(CONFIG_USB_DWC3)		+= dwc3/
#obj-$(CONFIG_USB_HISI_UDC)	+= hiudc/
#obj-$(CONFIG_USB_HISI_UDC3)+= hiudc3/

